### ISSUE TITLE
您好，关于您3年前的一篇代码，我有个问题

### ISSUE THREAD

**Issue by jiumoshou** [jinfeijie/nginx-server#4]
我之前发现了您的这篇代码  https://gist.github.com/jinfeijie/d0f6a4c90f9d50faf7d88788ee34c717
我现在在安卓native中使用了您的代码，想从native层进行网络交互
我在我的服务器端看到了访问请求和回复，但是在安卓native中不支持printf打印日志，我尝试打印返回的“n”参数，但是为空，所以我不知道该如何拿到服务器返回的json字符串数据。请求指导，谢谢。

**Comment by jinfeijie** [comment]
printf只是一个输出而已，你换成别的输出方式也没有问题的，需要检查请求是否能到达服务器

**Comment by jiumoshou** [comment]
到达服务器了，我找到拿到服务器返回数据的方法了，在解析返回的字符串了，谢谢大佬~
